name: Fletcher Place Neighborhood
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49054
title: Fletcher Place Neighborhood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58595b'
    - '#aaa485'
    - '#ffda39'
    - '#231f20'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.8408425350207835
purpose: []
